site_name: Hammerhead ROS2
docs_dir: docs
site_dir: site
theme:
  name: dracula
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    - content.code.copy
    - toc.integrate
    - palette.toggle
  palette:
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  logo: images/shark.svg
  favicon: images/shark.svg

extra_css:
  - css/main.css

extra_javascript:
  - js/logo-click.js

extra:
  generator: false

nav:
  - Home: index.md
  - License: license.md
  - Python Examples:
      - Generate ROS2 Bag: examples/python/generate_rosbag2_py.md
      - Image Viewer: examples/python/image_viewer_py.md
      - Obstacle Data Recorder: examples/python/obstacle_data_recorder_py.md
      - Point Cloud Generator: examples/python/point_cloud_generator_py.md
      - Camera Parameter Control: examples/python/set_camera_params_py.md
      - Toggle Recording: examples/python/toggle_recording_py.md
  - C++ Examples:
      - Generate ROS2 Bag: examples/cpp/generate_rosbag2.md
      - Image Viewer: examples/cpp/image_viewer.md
      - Obstacle Data Recorder: examples/cpp/obstacle_data_recorder.md
      - Point Cloud Generator: examples/cpp/point_cloud_generator.md
      - Camera Parameter Control: examples/cpp/set_camera_params.md
      - Toggle Recording: examples/cpp/toggle_recording.md


markdown_extensions:
  - toc
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: false
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
